spring:
  application:
    name: core-api

  datasource:
    url: jdbc:postgresql://localhost:5432/marketpulse
    username: marketpulse
    password: marketpulse

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: core-api
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.buchu.marketpulse.price.PriceUpdatedEvent
        spring.json.use.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

jwt:
  secret: D)Z1Z2sHF^%Uda(l;tq}nmdHWenq83w=)d
  expiration-ms: 3600000          # access: 1 hora
  refresh-expiration-ms: 604800000  # refresh: 7 días