spring:
  application:
    name: core-api

  datasource:
    url: jdbc:postgresql://localhost:5432/marketpulse
    username: marketpulse
    password: marketpulse

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

jwt:
  secret: D)Z1Z2sHF^%Uda(l;tq}nmdHWenq83w=)d
  expiration-ms: 3600000